# RDF predicates should be defined in an ontology
CONSTRUCT {
?p 	a	<http://scorpio4.com/v1/examples/mojo/check/undefined_property>
} WHERE {
	?s ?p ?o.
	OPTIONAL {
		?p rdfs:isDefinedBy ?onto.
	}
	FILTER(!BOUND(?onto))
}
