# RDF predicates should be defined in an ontology
CONSTRUCT {
?p 	a	<urn:scorpio4:demo:toolchain:factcheck:undefined_property>
} WHERE {
	?s ?p ?o.
	OPTIONAL {
		?p rdfs:isDefinedBy ?onto.
	}
	FILTER(!BOUND(?onto))
}
